---
all:
  children:
    molecule:
      hosts:
        instance:
          mp:
            podman:
              image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
            docker:
              image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
            kubevirt:
              boot_source:
                type: container_disk
                image: quay.io/containerdisks/centos-stream:9
              ssh_user: cloud-user
            qemu:
              image: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
              ssh_user: cloud-user
