---
# meta file for david_igou.linux_baseline.common

galaxy_info:
  role_name: common
  author: david_igou
  description: Common security hardening baseline settings for Linux systems
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - "41"
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - system
    - security
    - hardening

dependencies: []
