---
- name: Converge — apply chrony role
  hosts: molecule
  become: true
  gather_facts: true
  vars:
    chrony_enabled: true
    chrony_pool_servers:
      - "0.pool.ntp.org"
    chrony_drift_file: "/var/lib/chrony/drift"
    chrony_makestep: "1.0 3"
    chrony_leapsecmode: "ignore"
    chrony_log_interval: -1
    chrony_access_network: "192.168.0.0"
    chrony_access_mask: "/16"
    chrony_access_ro: true
  roles:
    - role: david_igou.linux_baseline.chrony
