---
# handlers file for david_igou.linux_baseline.sshd
- name: Reload sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
  listen: "Reload sshd"
  failed_when: false
  changed_when: false
