objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    journald_option:
      description: Set or remove journald.conf directives
      name: journald_option
      namespace: ''
      version_added: 1.0.0
    sshd_option:
      description: Set or remove sshd_config directives
      name: sshd_option
      namespace: ''
      version_added: 1.0.0
    sysctl_profile:
      description: Manage sysctl drop-in files in /etc/sysctl.d/
      name: sysctl_profile
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.0
